faebryk/faebryk

faebryk/exporters/netlist/kicad/netlist_kicad.py, faebryk/exporters/netlist/netlist.py, test/exporters/netlist/kicad/test_netlist_kicad.py
Instead of using dicts and tuples introduce a few data classes with
equivalent fields. These fields must exists, so nothing is lost
by not using dicts/tuples.
The class definitions also serve to document the structure of the
netlist.
=> Netlist: Refactor

README.md
Add extra img.shields.io labels for Discord, PyPi, commit activity
Fixes #67 
- New feature (non-breaking change which adds functionality)
=> Meta: Discord, PyPi, commit activity labels

faebryk/library/core.py, faebryk/library/library/components.py, faebryk/library/traits/component.py, samples/iterative_design_nand.py, samples/resistors_and_nand.py, test/exporters/netlist/kicad/test_netlist_kicad.py
Add backref to faebrykliboject when making trait part of object.
Remove manual backlinks in traits that used those before.
Fixes #49 
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Core: Add backref in traits to their object

.github/pull_request_template.md
Remove the pull request type from the template as it is redundant
(already in the pr tag)
Fixes #79 
=> PR template: Remove pr type

.github/CODEOWNERS
Fix for wrong github name (used alias instead of real ID).
Fixes #60 
=> Fix: Owner for .md files

faebryk/library/library/parameters.py
Add a ranged parameter (min/max)
=> Library: Add Ranged parameter

README.md
Add 5Ws (what, how, who, why, when, where) about faebryk
Fix markdown code blocks
=> Readme: Add 5Ws about faebryk

faebryk/exporters/netlist/graph.py
Throw faebryk exception if pin of target not in target pinmap.
Cleaner exception for pinmap problems while building graph.
=> Graph: Handle pin not in map explicitly

samples/iterative_design_nand.py, samples/resistors_and_nand.py
Export to build directory into a file instead of stdout.
=> Samples: Export to file

.gitmodules, requirements.txt, test/__init__.py, test/deps/__init__.py, test/exporters/netlist/kicad/test_sexp.py
Deps: Replace sexp_parser with sexpdata
Replace sexp_parser with a more stable/popular library that has a pip
module. Removing the need for git submodule.
=> Deps: Replace sexp_parser with sexpdata

faebryk/exporters/netlist/netlist.py
Add if statement to allow for names that do not start with `COMP[`
Co-authored-by: IoannisP-ITENG
Fixes #114 
=> Bugfix: Netlist: Use kicad ref if available for edge names

test/library/test_core.py
assertEquals is deprecated, use assertEqual instead.
=> Replace deprecated function calls in test code

README.md, examples/iterative_design_nand.py, examples/resistors_and_nand.py, requirements.txt, test/exporters/netlist/kicad/test_sexp.py, test/library/library/test_footprints.py, test/library/test_core.py
Update the install instructions Readme, including a description on how to use editable installs.
Remove redundant manual package include code.
=> Use editable install for development

src/faebryk/libs/kicad/parser.py
Added "fields" (export.components.comp.fields) field in netlist importer to ignore.
=> Bugfix: add "fields" to netlist importer

src/faebryk/exporters/netlist/graph.py, src/faebryk/library/core.py, src/faebryk/libs/kicad/parser.py, src/faebryk/libs/util.py, tools/symbol_converter/main.py
- Add heuristic for pin naming: pin_no string
- Remove aliasing
- Remove hiding
- Group same-name pins into list
=> Bugfix: Tools: Fix aliased pins in converter

src/faebryk/exporters/netlist/kicad/netlist_kicad.py
Bugfix: Exporter: Handle none extra_comps
Handle "None" case for extra_comps properly (operator precedence was wrong)
=> Bugfix: Exporter: Handle none extra_comps

src/faebryk/libs/picker/lcsc.py, src/faebryk/libs/picker/picker.py
Adds an optional PartIdentifier to a Part, which describes the partnumber, manufacturer, and datasheet.
This could be used for BOM exports.
Fixes #165
=> Part: Add PartIdentifier (mfr, p/n, datasheet)

src/faebryk/library/Diode.py, src/faebryk/library/TVS.py
Adds reverse_breakdown_voltage to TVS
Move reverse_working_voltage from TVS to Diode, and add reverse_leakage_current to Diode.
=> Lib: Diode: Add parameters, move Vrwm to Diode

src/faebryk/core/util.py, src/faebryk/library/Capacitor.py, src/faebryk/library/Resistor.py, src/faebryk/library/has_simple_value_representation_based_on_params.py
Let has_simple_value_representation_based_on_params, as_unit, and as_unit_with_tolerance accept any parameter.
=> Lib: accept all params for simple_value_rep

src/faebryk/libs/picker/lcsc.py, test/libs/lcsc.py
Slightly improves the 3D model translation situation by optimizing for
SMD passives and other components that have a zero offset at the cost
of worsening some other SMD components translation.
=> LCSC: Workarounds for 3D model translation

src/faebryk/exporters/pcb/layout/typehierarchy.py
The hierarchy needs to be applied to all nodes, even if they already
have a position.
The actual end layouts will take care of not overriding the position.
=> Bugfix: LayoutTypeHierarchy should not filter

examples/pcb_layout.py, src/faebryk/exporters/pcb/kicad/transformer.py, src/faebryk/exporters/pcb/layout/extrude.py, src/faebryk/exporters/pcb/layout/typehierarchy.py, src/faebryk/libs/util.py
Properly apply child layouts
Add possibility for type tuple
Transformer: Fix layer fp placement
Example: Make pcb-layout simpler
=> Bugfix: Layout: TypeHierarchy children layouts

poetry.lock, pyproject.toml, src/faebryk/libs/app/pcb.py, src/faebryk/libs/kicad/pcb.py, test/libs/kicad/pcb.py
Add a minimal encode/decode for kicad_prj files.
From here its easy to make it complete if its ever necessary.
Main purpose is to edit the netlist path in the last_paths.
This makes pcbnew point to the netlist per default.
=> Exporter: Add prj encode/decode; Set netlist path

src/faebryk/library/Switch.py
Bugfix: Library: isinstance for Switch
Makes use of `isinstance` possible on Switch
example for electrical interface switch:
```python
F.Switch(Electrical).is_instance(x):
```
=> Bugfix: Library: isinstance for Switch

src/faebryk/library/GenericBusProtection.py, src/faebryk/library/_F.py
Adds GenericBusProtection which adds fuses to power and TVS to all Electrical which can be surge protected.
=> Lib: Add GenericBusProtection Lib: Add GenericBusProtection

src/faebryk/library/ElectricLogic.py
Adds a push_pull parameter and enum to the ElectricLogic type, so it can be specified if it is push pull, open drain, or open source.
This can be useful to pick parts which have an open-drain output, by checking the push_pull parameter of the output interface.
=> Lib: ElectricLogic: add PushPull

src/faebryk/libs/kicad/fileformats.py, src/faebryk/libs/sexp/dataclass_sexp.py, src/faebryk/libs/util.py, test/libs/kicad/fileformats.py, test/libs/util.py
Kicad has some weird enums with a default being an empty string, which in the sexp becomes just non-existing.
Add support for those cases by skipping the enum field during positional argument parsing if "" is an option.
=> SEXP: Support empty enums & Simple unions

README.md, pyproject.toml, src/faebryk/libs/tools/typer.py, src/faebryk/tools/libadd.py, src/faebryk/tools/main.py, src/faebryk/tools/project.py
Add central faebryk command to run other tools
Add tools/project that helps instantiate the project_template
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Tools: Add faebryk command; Add tools/project (#10)
