source/library.py

Prohibit connecting non existing pins to each other.

Library: Prohibit connecting non existing pins

---

faebryk/exporters/netlist/netlist.py
faebryk/library.py
faebryk/libs/__init__.py
faebryk/libs/exceptions.py

Core: Throw error if graph edge to an unkown node

---

README.md

Updated the link to infinite invites + no expiration date
Fixes #37 
Please read and execute the folowing:
How can we get in touch with you if we need more info?
\-

Fix: Expired Discord link

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Change the labels, and titles
Fixes #42 
Please read and execute the folowing:
How can we get in touch with you if we need more info?

Add correct label and title to issue templates

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

- Fixing some typos
- Changing some words
- Add link to COC
Fixes #52 
Please delete options that are not relevant.
Please read and execute the folowing:

Template fixes and removals

---

.gitignore

Adds _local as ignored dir in gitignore to have standardized space for
playing around.
New feature (non-breaking change which adds functionality)
- [x I agree to follow this project's [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md)

Meta: Ignore _local folder in gitignore

---

scripts/clean_issues.py

Add helper script to clean github issues.
Uses github cli.
New feature (non-breaking change which adds functionality)

Scripts: clean issues script

---

samples/iterative_design_nand.py
samples/resistors_and_nand.py

Add top-of-file comment to the current samples.
Fixes #64 
New feature (non-breaking change which adds functionality)

Sample: Add explanation to current examples

---

README.md

Meta: Add pip instructions to README
Add instructions how to install faebryk with pip to README.
Fixes #66 
New feature (non-breaking change which adds functionality)

Meta: Add pip instructions to README

---

faebryk/library/library/footprints.py
test/library/__init__.py
test/library/library/__init__.py
test/library/library/test_footprints.py

Adds a generic QFN footprint to library.
Fixes `<no issue>`
- New feature (non-breaking change which adds functionality)

Library: Add QFN footprint

---

.git-blame-ignore-revs

Github rebase & merge changed commit id of black commit.
Please delete options that are not relevant (and this text).
- Bug fix (non-breaking change which fixes an issue)

Meta: Bugfix: Fix git blame ignore revs for black

---

faebryk/exporters/netlist/kicad/netlist_kicad.py
samples/iterative_design_nand.py
samples/resistors_and_nand.py
scripts/clean_issues.py
test/exporters/netlist/kicad/test_netlist_kicad.py
test/exporters/netlist/kicad/test_sexp.py

Changed print functions to logger functions.
Fixes #46 

Change: Print to logging

---

faebryk/library/library/components.py

Add capacitor to the component library. This is basically the same as a resistor but with different type descriptor.

Add: Capacitor to component library

---

faebryk/library/core.py
test/library/__init__.py
test/library/test_core.py

Test: Add core.trait tests
Add tests for verifying base functionality of traits
New tests are failing, but that's good since they identify a core issue.

Test: Add core.trait tests

---

faebryk/exporters/netlist/graph.py
faebryk/library/core.py
faebryk/library/library/components.py
faebryk/library/library/interfaces.py
faebryk/library/traits/component.py
faebryk/library/traits/interface.py
faebryk/library/util.py
samples/iterative_design_nand.py
samples/resistors_and_nand.py
test/exporters/netlist/kicad/test_netlist_kicad.py

Make interfaces a firm part of components.
Add connect helpers (_all, _via, _via_chain).

Core: Interface rework

---

README.md

The "a" in faebryk is "silent" so it's pronounced as febryk [fˈɛbɹɪk]

Readme: Add phonetic pronunciation

---

faebryk/library/core.py

Make connect_all compile
Fix type in connect_via

Bugfix: Fix connect_all

---

faebryk/exporters/netlist/netlist.py

Using the savefig command from madplotlib
Fixes #104 

Netlist: Add export graph to png functionality

---

README.md

This decreases friction on installation because it does not require authentication with github.

README: Use https:// instead of git protocol

---

README.md

Currently there are no test dependencies,so there is no point in having one.

Test: Remove test requiremets.txt

---

.pre-commit-config.yaml
examples/modules.py
examples/resistors_and_nand.py
faebryk/exporters/netlist/graph.py
faebryk/exporters/netlist/netlist.py
faebryk/exporters/project/faebryk/project_faebryk.py
faebryk/importers/netlist/kicad/netlist_kicad.py
faebryk/library/core.py
faebryk/library/kicad.py
faebryk/library/library/parameters.py
faebryk/library/trait_impl/component.py
faebryk/libs/pycodegen.py
faebryk/libs/util.py
requirements.txt
scripts/clean_issues.py
test/exporters/netlist/kicad/test_sexp.py
test/importers/netlist/kicad/test_netlist_kicad.py
test/integration/netlist/kicad2faebryk/test_netlist_kicad_2_faebryk_prj.py
test/library/library/test_footprints.py
test/test.py

Add black as pre-commit hook to run when committing.
Also ran the hook on all files to fix current formatting errors.

Meta: Add black pre-commit & run on all

---

examples/common/buildutil.py
examples/iterative_design_nand.py
examples/modules.py
examples/resistors_and_nand.py
faebryk/exporters/netlist/netlist.py

Make common example library.
Add export_graph & export_netlist.
Adapt samples to use those.
Fix sample imports.
Fixes #110 
Supersedes #109 

Samples: Improve and unify exporting

---

faebryk/library/core.py

Implement trait implementations that are not always actually implemented.
Use dynamic trait for interface is_part_of_component trait impl.

Core: Add dynamic trait implementations

---

docs/CODING_GUIDELINES.md

Documentation: Add pre-commit section

---

requirements.txt

Bugfix: Meta: Fix requirements syntax

---

pyproject.toml

Meta: Bump version to 2.0.0

---

README.md

Rename from sample to example.
Remove tail command.

Bugfix: Readme: Fix example instructions

---

.pre-commit-config.yaml
src/faebryk/exporters/netlist/graph.py
src/faebryk/exporters/netlist/kicad/netlist_kicad.py
src/faebryk/exporters/netlist/netlist.py
src/faebryk/library/trait_impl/component.py
src/faebryk/library/traits/component.py

Update pre-commit tools to newest versions
Exporter: Netlist: Add descriptive_properties trait and use
overriden_name
Exporter: Netlist: Kicad: Constrain name length
Exporter: Netlist: Fix component iteration

Bugfix: Pre-commit update; Kicad netlist fixes

---

src/faebryk/core/core.py
src/faebryk/library/Operation.py
src/faebryk/libs/picker/picker.py
src/faebryk/libs/util.py

Picker: Improve logging

---

src/faebryk/library/Constant.py
src/faebryk/library/Range.py
src/faebryk/library/Set.py

Add for Set, Range and Constant comparisons with other types
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Library: Implement non-equal parameter comparisons

---

src/faebryk/library/Capacitor.py

Use constant value name for temperature coefficient
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Library: Fix capacitor value repr

---

.github/workflows/pytest.yml
src/faebryk/exporters/netlist/kicad/netlist_kicad.py
src/faebryk/exporters/project/faebryk/project_faebryk.py
src/faebryk/library/Set.py
src/faebryk/libs/kicad/parser.py
test/core/test_parameters.py
test/exporters/netlist/kicad/test_sexp.py
test/importers/netlist/kicad/test_schematic_kicad.py
test/integration/netlist/kicad2faebryk/test_netlist_kicad_2_faebryk_prj.py

- CI: Add pytest workflow
- Library: Fix Set comparisons
- Test: Add parameter comparison tests
- Test: Ignore NotImplemented tests
- Lint: Fix ruff warnings/errors

CI: Add pytest workflow

---

src/faebryk/libs/picker/picker.py

Unpicked detector was untested and did not work.
Make it actually detect non-picked parts.

Picker: Fix unpicked detector

---

src/faebryk/exporters/bom/jlcpcb.py

Adds BOM exporter compatible with JLCPCB.

Exporters: BOM: Add JLCPCB BOM exporter

---

src/faebryk/library/Constant.py
src/faebryk/library/Range.py
src/faebryk/library/Set.py
src/faebryk/libs/e_series.py
test/libs/test_e_series.py

Add functions to get a list of E series values that are within a range or with a specified ratio.

Libs: Add E-series utilities

---

src/faebryk/exporters/bom/jlcpcb.py

Sort bomline designators by alphabetically designator prefix, and then by increasing number.
Sort bomlines by first designator prefix, and then by first designator number.
Results in:
```csv
Designator,...
"C1, C2, C3, C10",...
C4,...
"C5, C11",...
"C6, C7, C8, C9",...
"D1, D10",...
D2,...
F1,...
U1,...
```

Exporters: BOM: Sort bomlines by designator

---

src/faebryk/library/PowerSwitch.py
src/faebryk/library/PowerSwitchMOSFET.py
src/faebryk/library/PowerSwitchStatic.py
src/faebryk/library/_F.py

Add a generic PowerSwitch
Add PowerSwitchStatic, which just translates an ElectricLogic to an ElectricPower
Fix the pull direction of the resistor on PowerSwitchMOSFET

Lib: PowerSwitch: Add generic, static, and fix MOSFET

---

src/faebryk/libs/kicad/pcb.py

Add support for kicad8 file formats

Kicad: Add support for kicad8

---

src/faebryk/exporters/pcb/layout/font.py
src/faebryk/libs/geometry/basic.py

fix mirrored y-axis
fix resolution inverted
fix kerning not relative to resolution
fix bbox as alternative parameter

Fontlayout: fix bugs

---

src/faebryk/exporters/pcb/layout/font.py
src/faebryk/libs/geometry/basic.py

Revert "Fontlayout: fix bugs"

---

src/faebryk/exporters/pcb/kicad/transformer.py

Fixes the arcs between lines in the KiCad PCB transformer

Exporters: KiCad: Transformer: Fix connect_lines_via_radius

---

src/faebryk/libs/picker/picker.py

Picker now tells you which modules caused the failure.

Picker: Improve failure logging

---

src/faebryk/exporters/pcb/layout/absolute.py
src/faebryk/exporters/pcb/layout/extrude.py
src/faebryk/exporters/pcb/layout/typehierarchy.py

If a node already has a position don't overwrite it in layouts.

Layout: Don't overwrite pos

---

poetry.lock
pyproject.toml
src/faebryk/exporters/pcb/layout/font.py
src/faebryk/libs/font.py
src/faebryk/libs/geometry/basic.py

Fixes scaling to bbox
Add distributed points for fontlayout
Use freetype instead of fonttools
(Rebased version of #208)

Layout: Improve font for non-pixeled fonts

---

src/faebryk/libs/app/pcb.py
src/faebryk/libs/kicad/pcb.py

Add fp-lib-table encoder/decoder
Add hardcoded lcsc lib
Add include_footprints call in pcb app lib
Call include_footprints on apply_netlist call

Export fp table for custom footprints

---

src/faebryk/library/Comparator.py
src/faebryk/library/OpAmp.py
src/faebryk/library/_F.py

Adds a basic OpAmp and Comparator with most relevant parameters

Lib: Add Comparator and OpAmp

---

src/faebryk/exporters/pcb/layout/matrix.py

Distribute things in (x/y)matrix.

PCB: Layout: Add matrix layout

---

src/faebryk/exporters/parameters/parameters_to_file.py

Export all parameters of a given module (and its children) to a file.

Exporters: Parameters to file exporter

---

src/faebryk/exporters/pcb/kicad/transformer.py
src/faebryk/exporters/pcb/routing/routing.py
src/faebryk/libs/kicad/fileformats.py
src/faebryk/libs/sexp/dataclass_sexp.py
test/common/resources/test.kicad_pcb

Add support for more items commonly found in kicad files and extend existing items

Libs:KiCad: Extend fileformat

---

poetry.lock
pyproject.toml
src/faebryk/core/core.py
src/faebryk/core/graph.py
src/faebryk/core/graph_backends/default.py
src/faebryk/core/graph_backends/graphgt.py
src/faebryk/core/graph_backends/graphig.py
src/faebryk/core/graph_backends/graphnx.py
src/faebryk/core/graph_backends/graphpy.py
src/faebryk/core/util.py
src/faebryk/exporters/esphome/esphome.py
src/faebryk/exporters/netlist/graph.py
src/faebryk/exporters/netlist/netlist.py
src/faebryk/exporters/pcb/kicad/transformer.py
src/faebryk/exporters/pcb/routing/routing.py
src/faebryk/library/Constant.py
src/faebryk/library/Range.py
src/faebryk/library/Set.py
src/faebryk/libs/app/designators.py
src/faebryk/libs/app/erc.py
src/faebryk/libs/brightness.py
src/faebryk/libs/util.py
test/core/test_core.py
test/core/test_performance.py
test/core/test_util.py
test/exporters/netlist/kicad/test_netlist_kicad.py
test/libs/util.py

https://github.com/atopile/faebryk/pull/8

Merge: Core: Direct graph synthesis (atopile/faebryk#8)

---

src/faebryk/libs/kicad/fileformats.py

Add allow missing courtyard

---

src/faebryk/libs/picker/picker.py

Fix: libs: picker: import order

---

src/faebryk/exporters/pcb/layout/extrude.py
src/faebryk/exporters/pcb/layout/matrix.py

Fixed the matrix layout so it will work with uneven colum/rows and uneven nodes.
This will also place the nodes deterministicly in column then row order;
1 - 4 - 7
2 - 5 - 8
3 - 6 - 9
Added class descriptions to both extrude and matrix layouts.
Added dynamic rotation option to extrude; this will rotate each consecutive node with pre defined angle.

Bugfix: exporters: pcb layout matrix distribution

---

examples/iterative_design_nand.py
src/faebryk/core/core.py
src/faebryk/core/util.py
src/faebryk/library/Constant.py
src/faebryk/library/ElectricLogic.py
src/faebryk/library/LED.py
src/faebryk/library/Logic.py
src/faebryk/library/Operation.py
src/faebryk/library/PowerSwitchMOSFET.py
src/faebryk/library/Range.py
src/faebryk/library/Resistor.py
src/faebryk/library/Set.py
src/faebryk/library/TI_CD4011BE.py
src/faebryk/libs/e_series.py
src/faebryk/libs/examples/buildutil.py
src/faebryk/libs/examples/pickers.py
src/faebryk/libs/picker/jlcpcb/jlcpcb.py
src/faebryk/libs/picker/lcsc.py
src/faebryk/libs/picker/picker.py
src/faebryk/libs/util.py
test/core/test_parameters.py

* Fix: Examples iterative_design_nand
- Example: fix & modernize iterative_design_nand
- Params: allow failing eq for merge check
- Params: add unresolved range merge
- Holders: use self for holder class in super constructors (preparation for new datacls)
- CoreUtil: improve name based zipping of nodes
- CoreUtil: improve name based specialization
- Library: Logic: Add state param & set_weak
- Library: Fix PowerSwitchMOSFET
- Library: TI_CD4011BE add descriptive properties
- Example: Add switch picker
- Libs: LCSC only attach footprint if no fp attached
- Libs: fix recursive picker unnecessary retries
- Params: remove common code merge & intersect
- Params: fix merge
- Params: removed unresolved range merge
- Params: Add _resolved decorator for most ops
- Params: Add _SupportSetOps mixin …

Fix: Parameters & Module specialization (#16)

---

src/faebryk/core/core.py
src/faebryk/core/util.py
src/faebryk/library/ButtonCell.py
src/faebryk/library/LED.py
src/faebryk/library/Operation.py
src/faebryk/libs/e_series.py
src/faebryk/libs/picker/jlcpcb/jlcpcb.py
src/faebryk/libs/picker/jlcpcb/picker_lib.py
src/faebryk/libs/util.py
test/core/test_parameters.py
test/libs/picker/test_jlcpcb.py
test/libs/test_e_series.py

- Core: Fix inheritance
- Core: Params: Improve get_narrow
- Operation: fix repr
- Picker: JLCPCB e_series param for value
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fix: Module inheritance (#17)
